// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rookie_test
void rookie_test();
RcppExport SEXP _rookie_rookie_test() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    rookie_test();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rookie_rookie_test", (DL_FUNC) &_rookie_rookie_test, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rookie(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
